### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by rubenmoya** [trailsjs/generator-trails-old#74]
Hi mates!

We have currently the version `2.0.1`published in NPM, which has an old version of `eslint` and throws errors, that's fixed in the `2.0.3` version, could we publish it?

Thank you!

**Comment by jaumard** [comment]
generator-trails@2.0.3 is already published, but don't know why it's not the one shown on npm. @tjwebb can you take a look at this please ?

**Comment by konstantinzolotarev** [comment]
@rubenmoya @jaumard This package and most of other trails packages are publishing using TravisCI. So after creating a tag in repo it should be deployed into NPM.

@tjwebb Might be secret expired or was disabled ?
